# Generated by Django 4.2 on 2026-02-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الإشارة')),
                ('video', models.FileField(upload_to='avatars/', verbose_name='فيديو الأفاتار')),
                ('description', models.TextField(blank=True, verbose_name='وصف الحركات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إشارة أفاتار',
                'verbose_name_plural': 'إشارات الأفاتار',
                'ordering': ['-created_at'],
            },
        ),
    ]
